### PR TITLE
Fixed errors in build script for native build

### PR DESCRIPTION
**Pull request by peterk-code**
Corrected Docker file reference in build script to use corect Docker.builder file
Added argument passing in call to Docker base build
Switched Docker image reference from non-accesible repo to local reference

Fixes Issue: 19

### CODE REVIEW

**Comment by peterk-code** [comment]
Hey thanks for putting this together! DOODS is the best Tensorflow wrapper that I've seen. I tried to build locally per the instructions, but ran into a couple of small issues with the makefile and Docker files and  corrected here.

**Comment by snowzach** [comment]
Hey @peterk-code thanks a lot for the pull.. I have been working on reworking the Dockerfiles completely so each build type just has it's own file. They are redundant but it's a little more straight forward. Have a look at this branch: https://github.com/snowzach/doods/tree/rebuild

**Comment by peterk-code** [comment]
The re-write looks good! I'll give it a try tomorrow to make sure everything is working OK. Thanks!

**Comment by snowzach** [comment]
I am not sure if you use an edge-tpu but they broke something. Other than that it works fine

**Comment by peterk-code** [comment]
Just got some time to sit down and try the new build process and the output. Worked like a charm! Thanks a lot for the contribution.

**Comment by peterk-code** [comment]
I'm not using  edgetpu so can't test/debug that one, unfortunately.

**Comment by snowzach** [comment]
Ahh I fixed that issue also.. thanks

**Pull request closed without merging**
